[package]
name = "man_search"
version = "0.1.0"
edition = "2021"

[[bin]]
name = "index"
path = "src/bin/index.rs"

[[bin]]
name = "search"
path = "src/bin/search.rs"

[dependencies]
memmap2 = "0.9.10"
rust-stemmers = "1.0"
